[project]
authors = ["sayantikabanik <sayantikabanik122@gmail.com>"]
channels = ["conda-forge"]
description = "Intro to simple yet powerful python concepts"
name = "101_python"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]
101_kaggle_data = { cmd = "python fetch_online.py", cwd = "../dataset"}
dashboard = { cmd = "jupyter notebook simple_stock_price_analyse_dashboard.ipynb", cwd = "../dashboard" }

[dependencies]
python = ">=3.13.2,<3.14"
pip = ">=25.0.1,<26"
requests = ">=2.32.3,<3"
numpy = ">=2.2.4,<3"
pandas = ">=2.2.3,<3"
kagglehub = ">=0.3.8,<0.4"
panel = ">=1.6.2,<2"
bokeh = ">=3.7.2,<4"
holoviews = ">=1.20.2,<2"
