[project]
authors = ["sayantikabanik <sayantikabanik122@gmail.com>"]
channels = ["conda-forge"]
description = "Intro to simple yet powerful python concepts"
name = "101_python"
platforms = ["linux-64", "osx-arm64", "win-64"]
version = "0.1.0"

[tasks]

[dependencies]
python = ">=3.13.2,<3.14"
pip = ">=25.0.1,<26"
requests = ">=2.32.3,<3"
